http:
  addr: "192.168.100.4"
  port: 8080
  maxHeaderMIB: 1
  readTimeout: 10s
  writeTimeout: 10s

tcp:
  addr: "192.168.100.4"
  port: 4545
  bufLimitMIB: 2
  awaitConn: 10s

data:
  timeDuration: 20
  availableFields:
    TrackGrossWeight: "Общая масса, кг"
    TrackWidth: "Ширина, см"
    TrackWHeight: "Высота, см"
    TrackLength: "Длина, см"
  message: "Ведется весовой и габаритный контроль"